"""Image providers for the Visual Agent — JVL Content Engine.

Two providers:
  MockImageProvider   — returns None (no API calls); used when OPENAI_API_KEY is absent.
  OpenAIImageProvider — generates images via OpenAI's gpt-image models.

Factory:
  get_image_provider() → OpenAIImageProvider if OPENAI_API_KEY is set, else mock.

Shared utility:
  save_image(data, dest) → writes generated bytes to a local path.

Model and quality are per role and env-overridable:

  role    env vars                                    default
  hero    IMAGE_MODEL_HERO   / IMAGE_QUALITY_HERO     gpt-image-2 / medium
  inline  IMAGE_MODEL_INLINE / IMAGE_QUALITY_INLINE   gpt-image-1-mini / medium
"""

from __future__ import annotations

import base64
import os
import sys
from pathlib import Path


#: Model and quality per asset role.
#:
#: The hero is the one image every reader sees, so it gets the flagship. The
#: inline images sit mid-article and get the mini, which costs roughly a
#: quarter as much at the same quality tier. Quality matters more than model
#: for the bill: low→high is a ~30x spread within one model, where the models
#: differ by at most ~4x at a fixed tier.
_ROLE_DEFAULTS: dict[str, tuple[str, str]] = {
    "hero":   ("gpt-image-2", "medium"),
    "inline": ("gpt-image-1-mini", "medium"),
}


def resolve_model(role: str = "inline") -> str:
    """Return the configured image model for a role."""
    model, _ = _ROLE_DEFAULTS.get(role, _ROLE_DEFAULTS["inline"])
    return os.environ.get(f"IMAGE_MODEL_{role.upper()}", model)


def resolve_quality(role: str = "inline") -> str:
    """Return the configured quality tier for a role."""
    _, quality = _ROLE_DEFAULTS.get(role, _ROLE_DEFAULTS["inline"])
    return os.environ.get(f"IMAGE_QUALITY_{role.upper()}", quality)


# ---------------------------------------------------------------------------
# Providers
# ---------------------------------------------------------------------------

class MockImageProvider:
    """No-op provider. Returns None for every generate() call."""

    def generate(self, prompt: str, size: str, role: str = "inline") -> bytes | None:
        print("  [mock] Image generation skipped (no OPENAI_API_KEY).", file=sys.stderr)
        return None


class OpenAIImageProvider:
    """Generates images via OpenAI's gpt-image models."""

    def __init__(self) -> None:
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError("OPENAI_API_KEY is required for OpenAIImageProvider.")
        import openai
        self.client = openai.OpenAI(api_key=api_key)

    def generate(self, prompt: str, size: str, role: str = "inline") -> bytes | None:
        """Generate one image and return its PNG bytes.

        Bytes, not a URL: the gpt-image models answer only with base64 in
        `b64_json`. The temporary URL DALL-E 3 used to hand back has no
        equivalent here, so there is nothing left to download.

        Args:
            prompt: generation prompt.
            size:   "1536x1024" for hero, "1024x1024" for inline.
            role:   "hero" or "inline" — selects the model and quality tier.

        Returns:
            PNG bytes, or None on failure.
        """
        model = resolve_model(role)
        try:
            response = self.client.images.generate(
                model=model,
                prompt=prompt,
                size=size,
                quality=resolve_quality(role),
                n=1,
            )
            payload = response.data[0].b64_json
            if not payload:
                print(f"  {model} returned no image data.", file=sys.stderr)
                return None
            return base64.b64decode(payload)
        except Exception as exc:
            print(f"  {model} generation failed: {exc}", file=sys.stderr)
            return None


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

def get_image_provider() -> MockImageProvider | OpenAIImageProvider:
    """Return OpenAIImageProvider if OPENAI_API_KEY is set, else MockImageProvider."""
    if os.environ.get("OPENAI_API_KEY"):
        print(
            f"Image provider: OpenAI ({resolve_model('hero')} hero,"
            f" {resolve_model('inline')} inline)",
            file=sys.stderr,
        )
        return OpenAIImageProvider()
    print("Image provider: mock (set OPENAI_API_KEY for real generation)", file=sys.stderr)
    return MockImageProvider()


# ---------------------------------------------------------------------------
# Shared save utility
# ---------------------------------------------------------------------------

def save_image(data: bytes, dest: Path) -> Path:
    """Write generated image bytes to dest, creating parent directories.

    Args:
        data: raw image bytes as returned by a provider.
        dest: local destination path.

    Returns:
        The dest path after a successful write.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)
    return dest
